<a href="https://colab.research.google.com/github/SanjaySaatyaki/yt_ai_research/blob/main/4_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
t = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float32)

In [5]:
t.shape

torch.Size([2, 3])

In [10]:
t_falt = t.flatten()
t_falt.shape

torch.Size([6])

In [12]:
t_flat_start = t.flatten(start_dim=0)
t_flat_start

tensor([1., 2., 3., 4., 5., 6.])

In [20]:
d3_tensor = torch.tensor([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])

In [25]:
d3_tensor

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [27]:
d3_tensor.flatten(start_dim=1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [28]:
t = torch.tensor([[1,2,3,4],
                  [5,6,7,8]])

In [29]:
t.shape

torch.Size([2, 4])

In [30]:
t.reshape(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [32]:
t = torch.tensor([[[1,3,4]]])
t_squeeze = t.squeeze()

In [33]:
t_squeeze

tensor([1, 3, 4])